### ISSUE TITLE
Changement projet pour la contribution

### ISSUE THREAD

**Issue by TJoker024** [ploum/lingi2401#104]
Bonjour Mr Dricot, j'ai un problème avec mon choix de projet sur lequel je veux contribuer et j'aimerais changer de projet. Un ami m'a parler du projet https://github.com/Just-A-Visitor/Algorithmic-Pseudocode et j'aimerais y contribuer et de plus le gestionnaire du git est très actif  mais j'aimerais votre autorisation avant de me lancer .

**Comment by ploum** [comment]
pas de soucis.
