### ISSUE TITLE
Comments on the slides + notes for third course on business models

### ISSUE THREAD

**Issue by jerthiry** [ploum/lingi2401#11]
Hi everyone !

I know there are some additional notes on the code that generates the slides but is there a way to see them directly in the browser or should we dive into the source code to see them? 

Also, I couldn't make it to the class last week on business models. Would anyone have notes on this lesson and be willing to share them? 😃

**Comment by ploum** [comment]
When your are viewing at the slides in your browser, press P to see the comments (presentator mode)

**Comment by ploum** [comment]
If someone has notes on the course, I would be very interested to see if they could be merged with the slides. At worst, a separate file in the repository would be fine.
