### ISSUE TITLE
Is the Github page good enough to discuss?

### ISSUE THREAD

**Issue by ploum** [ploum/lingi2401#14]
I'm wondering if someone is notified when a ticket is created. And if something like a chat would be interesting. (currently testing keybase.io which is really interesting from an Open Source perspective).

**Comment by jerthiry** [comment]
For me it is good enough. I get an email for every new issue as I watch the repo.

**Comment by ploum** [comment]
Then that's perfect. Will tell the students to watch the repo tomorrow.
